### ISSUE TITLE
Debugging tests

### ISSUE THREAD

**Issue by DmitryAndreyeff** [pgourlain/vscode_erlang#124]
Hi there. Apologies for newbie question. 
How can I debug a test? I'm setting a breakpoint in the code and running "rebar3 ct" in the terminal, but nothing happens. Sorry if it's too basic question.

**Comment by pgourlain** [comment]
Hi,

There is no basic question !
Because debugging can only be run under an erlang shell. Why ?
1) When the debugger is started under VisualStudio Code, there is a link (network) between Erlang shell and VSCode
2) An erlangbridge is start with your application, and this bridge launch erlang debugger using 'int' module

So to debug your tests, you should start an erlang application, that launch your tests by executing eunit:test(MyModule).

**Comment by humanist1965** [comment]
Hi pgourlain. 
I'm also a struggling newbie and I'm keen to get my VSCode editor setup so I can debug Erlang code from it. Just trying to write simple test programs at the moment in a single test.erl file but I can not get the VSCode debugger to work.

Is it possible to use your debugger on a simple single *.erl file module?

Any help you can give would be much appreciated.
