### ISSUE TITLE
Search finds files in _build directory

### ISSUE THREAD

**Issue by wojteksurowka** [pgourlain/vscode_erlang#287]
Recent changes around exclude filters broke search in the unpleasant way which was long gone. I again now have a problem which I think I fixed years ago that features like Go to definition etc find files in _build directory, where I can modify them only to lose all changes during the next build.

Behaviour before: one could have exclude patterns (line e.g. node_modules for projects using both Erlang and npm) and _build directory was ignored in search, unless it was the only location for a file, which is the case for third-party dependencies

Behaviour now: if any exclude pattern is set _build directory is treated as any other directory, which means that e.g. definitions are found in it. (I based this on the discussion in pull request, I did not try to delete all my exclude patterns to confirm).

Adding _build directory to exclude patterns would cause that searching for third party dependencies no longer works.

Looks like for the sake of exotic build system the life of users of the de facto standard rebar3 is now worse. This is a showstopper problem - if rebar3 is used, any solution which potentially opens files from _build directory which are copies of files from src is potentially damaging.

**Comment by pgourlain** [comment]
Hi Wojtek,

Sorry to hear that.
I will take a look.

**Comment by pgourlain** [comment]
Hi @wojteksurowka , @KornelH 

I choose to revert part of #285 .

I'm not developing on Erlang's huge projects like you. So your experiences are very useful for this extension.
I would like the better of both and understand your needs. In order to do that, if is possible for you. Would you filling a tiny ossature of your respective projects in this repo https://github.com/pgourlain/vscode_erlang_sandbox

any suggestions are welcome.

**Comment by KornelH** [comment]
@wojteksurowka, please help me, because I don't fully understand the exact issue.

If my understanding is right, then:

* There is no `search.exclude`, `files.exclude` or `files.watcherExclude` filter for `_build` (or the actual build directory set in `rebar.config`) in VSC settings
* e.g. _"Go to definition"_ opens a file from `_build` directory that is actually a copy (sym-link) of the original source file in `src`

Is it correct?

Pull request #285 seems to be innocent to me as it only adds an exclude filter for Bazel build system, it doesn't change anything else. Are you sure you got this error after #285? The basic logic was changed in #265 like 11 months ago, I'd suspect that instead. Again, I say this after a very quick look, so maybe I follow a completely wrong clue.

**Comment by wojteksurowka** [comment]
@pgourlain I will work on creating a mini project similar in structure to projects I work on. Might take some time though.

**Comment by wojteksurowka** [comment]
@KornelH Your description is correct. Actually I continue to see the problem after the recent commit was reversed so what you are saying sounds correct. It is possible that the problem was present for quite some time and I did not notice it since generally it is hard to notice that a file just opened is not the file from src.

**Comment by KornelH** [comment]
Hi @wojteksurowka, Is there any news on the reproduction?

I suggest to re-revert the above commit, as it was agreed that has nothing to do with the reported issue.

**Comment by KornelH** [comment]
From other hand, I think, I know the phenomenon that caused the issue in @wojteksurowka's environment. I've seen that many times the extension got no or not complete configuration from VSC, for example some configuration was up-to-date according the the workspace settings but search exclude filters were not there. I have no idea what can cause this misalignment, I couldn't figure it out yet, but I don't think it's due to this extension.

**Comment by wojteksurowka** [comment]
@KornelH @pgourlain I locally reverted #288 and I confirm that the problem happens with and without #288. Looks like we introduced it earlier. I will work on finding the root cause, but looks like we can safely re-revert.

**Comment by pgourlain** [comment]
Hi @wojteksurowka,

Thanks for your investigation. I will re-revert #288

**Comment by wojteksurowka** [comment]
Fixed by #306
