### ISSUE TITLE
Make it possible to use rebar3 for debug launch

### ISSUE THREAD

**Issue by hengestone** [pgourlain/vscode_erlang#33]
Instead of just being able to specify arguments to `erl`, it's much more convenient to just launch `rebar3 shell` for debugging.

**Comment by pgourlain** [comment]
Hi,

Today, debugger is join to your app, by adding some Erl specific arguments that is not supported by rebar3 shell
Cmd line are executed in this order :
1) start debugger 
2) start listener on specific port to interact with erlangDebugger
3) start your app

**Comment by wojteksurowka** [comment]
I agree that using "rebar3 shell" command is not feasible. What is more, the main advantage of using it - to have all applications and dependencies in the path - is taken care of in the current setup. There is no longer need to add ebin directories with -pa in the debug arguments, since they are added automatically.
I propose to close this issue.
